### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by leankyr** [MiniDomo/Kattis#5]
hey JB!

https://github.com/leankyr/KattisProblems/blob/main/NumberFun/Program.cs
might you have any clue why I get a runtime error here and your solution does not?

Hope you are staying strong during those times.
cheers

**Comment by minidomo** [comment]
I know this response is longer overdue, but I believe I figured out why your code may be getting a runtime error.

The reason why you received a runtime error is because you read more lines than what was given. This is a result of using the type `byte` for your `i` variable on [line 29](https://github.com/leankyr/KattisProblems/blob/276d6b5ff33984f1d96418db4f8c76b49cf4e0ad/NumberFun/Program.cs#L29) of your code.

According to the problem description, the number of test cases, **N**, can be as large as 10,000. If we let **N** equal 10,000, then your loop will continue running indefinitely, resulting in it trying to read more lines. Note that integers types in C# have maximum and minimum values, including `byte` and `short`.  When an integer type is at its maximum value and you try to add to it, it will undergo integer overflow. Ultimately, the type `byte` in your code is preventing the condition `i < N` from being false making your for loop run indefinitely. I would recommend changing the type to at least a `short` in order to fix your issue.

**Comment by leankyr** [comment]
OK thanks! I guess I did not notice the 10.000 number of test cases. And I was using the byte in an effort to save memory. Since Short goes from -32,768 to 32,767 i would cover my case so I would be fine! Thanks for the responce nevertheless.
