### ISSUE TITLE
This approach doesn't make sense to me.

### ISSUE THREAD

**Issue by at758** [MiniDomo/Kattis#6]
https://github.com/minidomo/Kattis/blob/ae2a50f48b9d654f18dcdfdcb05d7354338cc7d7/Java/basketballoneonone.java#L8

Doesn't work for this test case

```
A2A2A2A2A2B2B2B2B2B2A2B1A2B1
```

**Comment by minidomo** [comment]
The test case you've given is not valid considering the rules of the problem. To be specific, it does not follow the third rule
> If the score is tied 10–10, the previous rule is replaced by a “win by 2” rule: the first player to lead the other by at least two points wins.

With your test case, the first part of it, `A2A2A2A2A2B2B2B2B2B2`, leads to tied score of 10-10. Following this is `A2`. Therefore, the score becomes 12-10 and Alice wins based on the third rule as stated above. 

The problem also says the following under **Input**:
> Each record will be a correct scoring history of a single completed game, played under the rules described above.

According to this, your test case is not a correct scoring history because it continues to have history of scores despite the game ending prior. 

To describe my approach to this problem is fairly simple. Based on the rules of the game and how the scoring history ends when a player wins, the player that last scored will be the winner. Therefore, I print the second to last character from the given input.
